/**
 * This class is generated by jOOQ
 */
package org.my.ws.domain;


import javax.annotation.Generated;

import org.my.ws.domain.tables.Author;
import org.my.ws.domain.tables.Book;
import org.my.ws.domain.tables.BookStore;
import org.my.ws.domain.tables.BookToBookStore;
import org.my.ws.domain.tables.Language;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.LANGUAGE
	 */
	public static final Language LANGUAGE = org.my.ws.domain.tables.Language.LANGUAGE;

	/**
	 * The table PUBLIC.AUTHOR
	 */
	public static final Author AUTHOR = org.my.ws.domain.tables.Author.AUTHOR;

	/**
	 * The table PUBLIC.BOOK
	 */
	public static final Book BOOK = org.my.ws.domain.tables.Book.BOOK;

	/**
	 * The table PUBLIC.BOOK_STORE
	 */
	public static final BookStore BOOK_STORE = org.my.ws.domain.tables.BookStore.BOOK_STORE;

	/**
	 * The table PUBLIC.BOOK_TO_BOOK_STORE
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = org.my.ws.domain.tables.BookToBookStore.BOOK_TO_BOOK_STORE;
}
